services:
  air1-news:
    image: ghcr.io/haenlau/newsnow:latest
    container_name: air1-news
    ports:
      - '4444:4444'
    volumes:
      - air1_news_data:/usr/app/.data
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true

volumes:
  air1_news_data:
    name: air1_news_data
