services:
  air1-news:
    build: .
    ports:
      - '4444:4444'
    volumes:
      - air1_news_data:/usr/app/.data
    environment:
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true

volumes:
  air1_news_data:
    name: air1_news_data
